package aprendizado.poo.ProjetoSimuladoMVC.src.br.edu.ifpr.irati.ads.visao;

import br.edu.ifpr.irati.ads.controle.Controle;
import br.edu.ifpr.irati.ads.modelo.EstadoResposta;
import br.edu.ifpr.irati.ads.modelo.Questao;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

public class SimuladoGUI extends javax.swing.JFrame {

    private final JCheckBox checkBoxes[];
    private final CheckBoxHandler boxHandler;    
    private final Controle controle;
    

    public SimuladoGUI(Controle controle) {
        initComponents();
        this.controle = controle;
        initialAdjustments();
        DefaultComboBoxModel model
                = new DefaultComboBoxModel<>(controle.getProva().getQuestoes().toArray());
        jComboBoxEscolhaQuestao.setModel(model);
        jComboBoxEscolhaQuestao.addItemListener(new ComboBoxHandler());
        boxHandler = new CheckBoxHandler();
        jCheckBoxOp01.addItemListener(boxHandler);
        jCheckBoxOp02.addItemListener(boxHandler);
        jCheckBoxOp04.addItemListener(boxHandler);
        jCheckBoxOp08.addItemListener(boxHandler);
        checkBoxes = new JCheckBox[4];
        checkBoxes[0] = jCheckBoxOp01;
        checkBoxes[1] = jCheckBoxOp02;
        checkBoxes[2] = jCheckBoxOp04;
        checkBoxes[3] = jCheckBoxOp08;
        this.atualizarQuestaoTela();

    }

    public void initialAdjustments() {       
        jCheckBoxOp000.setVisible(false);
        jCheckBoxOp16.setVisible(false);
        this.setIconImage(new ImageIcon(getClass().getResource("/assets/prova.png")).getImage());
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setTitle("Simulado do PSS [" + controle.getCandidato().getCpf() + "]");
    }

    private double corrigirQuestao() {

        EstadoResposta estado[] = controle.obterEstadoResposta();
        for (int i = 0; i < estado.length; i++){
            if (estado[i] == EstadoResposta.MARCOU_CERTO){
                checkBoxes[i].setForeground(Color.BLUE);
            }else if (estado[i] == EstadoResposta.MARCOU_ERRADO){
                checkBoxes[i].setForeground(Color.red);
            }else{
                checkBoxes[i].setForeground(Color.BLACK);
            }
        }
        return controle.corrigirQuestao();

    }

    public void atualizarQuestaoTela() {
        jLabelDisciplina.setText(
                controle.getQuestaoAtual().getDisciplina().getNome().toUpperCase());
        jLabelNumeroQuestao.setText("QUESTÃO " + controle.getQuestaoAtual().getNumero());
        jTextAreaTextoQuestao.setText(
                controle.getQuestaoAtual().getTextoIntrodutorio() + "\n"
                + controle.getQuestaoAtual().getEnunciado());

        jCheckBoxOp01.setText(getHTML("01) " + controle.getQuestaoAtual().getAlternativas()[0].getTexto()));
        jCheckBoxOp02.setText(getHTML("02) " + controle.getQuestaoAtual().getAlternativas()[1].getTexto()));
        jCheckBoxOp04.setText(getHTML("04) " + controle.getQuestaoAtual().getAlternativas()[2].getTexto()));
        jCheckBoxOp08.setText(getHTML("08) " + controle.getQuestaoAtual().getAlternativas()[3].getTexto()));
        if (controle.getQuestaoAtual().getFigura().equals("")) {
            jButtonImagemQuestao.setEnabled(false);
        } else {
            jButtonImagemQuestao.setEnabled(true);
        }

        //aplicar check nas caixas de seleção que resultam no somatorio
        boxHandler.setMudar(false);
        boolean arrayGabarito[] = controle.obterArrayMarcacao(controle.getRespostaAtual().getSoma());
        for (int i = 0; i < arrayGabarito.length; i++) {
            checkBoxes[i].setSelected(arrayGabarito[i]);
        }
        boxHandler.setMudar(true);
        jTextFieldSomatorio.setText(String.valueOf(controle.getRespostaAtual().getSoma()));

    }

    private String getHTML(String input) {
        StringBuilder sb = new StringBuilder();
        sb.append("<html>");
        sb.append(input);
        sb.append("</html>");
        return sb.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEscolhaQuestao = new javax.swing.JPanel();
        jComboBoxEscolhaQuestao = new javax.swing.JComboBox<>();
        jPanelComandos = new javax.swing.JPanel();
        jPanelComandosEsquerda = new javax.swing.JPanel();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jPanelComandosDireita = new javax.swing.JPanel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonCorrigir = new javax.swing.JButton();
        jPanelElementosQuestao = new javax.swing.JPanel();
        jPanelElementosQuestaoEsquerda = new javax.swing.JPanel();
        jPanelElementosQuestaoEsquerdaDisciplina = new javax.swing.JPanel();
        jLabelDisciplina = new javax.swing.JLabel();
        jPanelElementosQuestaoEsquerdaEnunciado = new javax.swing.JPanel();
        jPanelElementosQuestaoEsquerdaCentral = new javax.swing.JPanel();
        jPanelElementosQuestaoEsquerdaCentralCabecalho = new javax.swing.JPanel();
        jPanelElementosQuestaoEsquerdaCabecalhoNumero = new javax.swing.JPanel();
        jLabelNumeroQuestao = new javax.swing.JLabel();
        jPanelElementosQuestaoEsquerdaCabecalhoImagem = new javax.swing.JPanel();
        jButtonImagemQuestao = new javax.swing.JButton();
        jPanelElementosQuestaoEsquerdaCentralTexto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTextoQuestao = new javax.swing.JTextArea();
        jPanelElementosQuestaoDireita = new javax.swing.JPanel();
        jCheckBoxOp000 = new javax.swing.JCheckBox();
        jCheckBoxOp01 = new javax.swing.JCheckBox();
        jCheckBoxOp02 = new javax.swing.JCheckBox();
        jCheckBoxOp04 = new javax.swing.JCheckBox();
        jCheckBoxOp08 = new javax.swing.JCheckBox();
        jCheckBoxOp16 = new javax.swing.JCheckBox();
        jPanelElementosQuestaoDireitaSomatorio = new javax.swing.JPanel();
        jTextFieldSomatorio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelEscolhaQuestao.setLayout(new java.awt.GridLayout(1, 0));

        jComboBoxEscolhaQuestao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBoxEscolhaQuestao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelEscolhaQuestao.add(jComboBoxEscolhaQuestao);

        getContentPane().add(jPanelEscolhaQuestao, java.awt.BorderLayout.PAGE_START);

        jPanelComandos.setLayout(new java.awt.GridLayout(1, 2));

        jPanelComandosEsquerda.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonAnterior.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/seta-esquerda.png"))); // NOI18N
        jButtonAnterior.setToolTipText("Ir para a questão anterior");
        jPanelComandosEsquerda.add(jButtonAnterior);

        jButtonProximo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/seta-direita.png"))); // NOI18N
        jButtonProximo.setToolTipText("Ir para a próxima questão.");
        jPanelComandosEsquerda.add(jButtonProximo);

        jPanelComandos.add(jPanelComandosEsquerda);

        jPanelComandosDireita.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonLimpar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/limpar.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setToolTipText("Limpar as respostas da questão.");
        jPanelComandosDireita.add(jButtonLimpar);

        jButtonCorrigir.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonCorrigir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/verifica.png"))); // NOI18N
        jButtonCorrigir.setText("Corrigir");
        jButtonCorrigir.setToolTipText("Corrigir a questão");
        jButtonCorrigir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCorrigirActionPerformed(evt);
            }
        });
        jPanelComandosDireita.add(jButtonCorrigir);

        jPanelComandos.add(jPanelComandosDireita);

        getContentPane().add(jPanelComandos, java.awt.BorderLayout.PAGE_END);

        jPanelElementosQuestao.setLayout(new java.awt.GridLayout(1, 0));

        jPanelElementosQuestaoEsquerda.setLayout(new java.awt.BorderLayout());

        jLabelDisciplina.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDisciplina.setText("DISCIPLINA");
        jPanelElementosQuestaoEsquerdaDisciplina.add(jLabelDisciplina);

        jPanelElementosQuestaoEsquerda.add(jPanelElementosQuestaoEsquerdaDisciplina, java.awt.BorderLayout.PAGE_START);

        jPanelElementosQuestaoEsquerdaEnunciado.setLayout(new java.awt.GridLayout(1, 0));
        jPanelElementosQuestaoEsquerda.add(jPanelElementosQuestaoEsquerdaEnunciado, java.awt.BorderLayout.PAGE_END);

        jPanelElementosQuestaoEsquerdaCentral.setLayout(new java.awt.BorderLayout());

        jPanelElementosQuestaoEsquerdaCentralCabecalho.setLayout(new java.awt.GridLayout(1, 0));

        jPanelElementosQuestaoEsquerdaCabecalhoNumero.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelNumeroQuestao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNumeroQuestao.setText("QUESTÃO 1");
        jPanelElementosQuestaoEsquerdaCabecalhoNumero.add(jLabelNumeroQuestao);

        jPanelElementosQuestaoEsquerdaCentralCabecalho.add(jPanelElementosQuestaoEsquerdaCabecalhoNumero);

        jPanelElementosQuestaoEsquerdaCabecalhoImagem.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonImagemQuestao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonImagemQuestao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/galeria.png"))); // NOI18N
        jButtonImagemQuestao.setText("Ver imagem");
        jButtonImagemQuestao.setToolTipText("Ver imagens associadas à questão.");
        jButtonImagemQuestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImagemQuestaoActionPerformed(evt);
            }
        });
        jPanelElementosQuestaoEsquerdaCabecalhoImagem.add(jButtonImagemQuestao);

        jPanelElementosQuestaoEsquerdaCentralCabecalho.add(jPanelElementosQuestaoEsquerdaCabecalhoImagem);

        jPanelElementosQuestaoEsquerdaCentral.add(jPanelElementosQuestaoEsquerdaCentralCabecalho, java.awt.BorderLayout.PAGE_START);

        jPanelElementosQuestaoEsquerdaCentralTexto.setLayout(new java.awt.GridLayout(1, 0));

        jTextAreaTextoQuestao.setEditable(false);
        jTextAreaTextoQuestao.setBackground(getBackground());
        jTextAreaTextoQuestao.setColumns(350);
        jTextAreaTextoQuestao.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jTextAreaTextoQuestao.setLineWrap(true);
        jTextAreaTextoQuestao.setRows(30);
        jTextAreaTextoQuestao.setText("Considerando o movimento do caule em direção à luz e a ação da auxina, observe a imagem abaixo e assinale o que for correto.");
        jTextAreaTextoQuestao.setDisabledTextColor(getBackground());
        jScrollPane1.setViewportView(jTextAreaTextoQuestao);

        jPanelElementosQuestaoEsquerdaCentralTexto.add(jScrollPane1);

        jPanelElementosQuestaoEsquerdaCentral.add(jPanelElementosQuestaoEsquerdaCentralTexto, java.awt.BorderLayout.CENTER);

        jPanelElementosQuestaoEsquerda.add(jPanelElementosQuestaoEsquerdaCentral, java.awt.BorderLayout.CENTER);

        jPanelElementosQuestao.add(jPanelElementosQuestaoEsquerda);

        jPanelElementosQuestaoDireita.setLayout(new java.awt.GridLayout(7, 1));

        jCheckBoxOp000.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jCheckBoxOp000.setText("...");
        jPanelElementosQuestaoDireita.add(jCheckBoxOp000);

        jCheckBoxOp01.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jCheckBoxOp01.setText("<html>01) O crescimento orientado da planta em resposta a um estímulo luminoso, tal como o observado na imagem acima, é chamado de fototropismo. </html>");
        jPanelElementosQuestaoDireita.add(jCheckBoxOp01);

        jCheckBoxOp02.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jCheckBoxOp02.setText("A imagem representa um caso de nastismo, em que a plântula não responde ao estímulo externo");
        jPanelElementosQuestaoDireita.add(jCheckBoxOp02);

        jCheckBoxOp04.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jCheckBoxOp04.setText("O fototropismo, diferente de outros tropismos, pode ser apenas positivo, sendo observado tanto no caule como na raiz.");
        jPanelElementosQuestaoDireita.add(jCheckBoxOp04);

        jCheckBoxOp08.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jCheckBoxOp08.setText("A luz faz com que a auxina seja translocada para o lado sombreado do ápice em crescimento, onde estimula o alongamento celular, promovendo a curvatura do caule em direção à fonte de luz.");
        jPanelElementosQuestaoDireita.add(jCheckBoxOp08);

        jCheckBoxOp16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jCheckBoxOp16.setText("...");
        jPanelElementosQuestaoDireita.add(jCheckBoxOp16);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        jPanelElementosQuestaoDireitaSomatorio.setLayout(flowLayout1);

        jTextFieldSomatorio.setEditable(false);
        jTextFieldSomatorio.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextFieldSomatorio.setText("      ");        
        jPanelElementosQuestaoDireitaSomatorio.add(jTextFieldSomatorio);

        jPanelElementosQuestaoDireita.add(jPanelElementosQuestaoDireitaSomatorio);

        jPanelElementosQuestao.add(jPanelElementosQuestaoDireita);

        getContentPane().add(jPanelElementosQuestao, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImagemQuestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImagemQuestaoActionPerformed
        ImagemGUI imagemGUI
                = new ImagemGUI(controle.getQuestaoAtual().getFigura(),
                        "Imagem da Questão " + controle.getQuestaoAtual().getNumero());
        imagemGUI.setVisible(true);
    }//GEN-LAST:event_jButtonImagemQuestaoActionPerformed

    private void jButtonCorrigirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCorrigirActionPerformed
        double pontuacao = this.corrigirQuestao();
        JOptionPane.showMessageDialog(this, pontuacao);
    }//GEN-LAST:event_jButtonCorrigirActionPerformed

    private class ComboBoxHandler implements ItemListener {

        @Override
        public void itemStateChanged(ItemEvent e) {
            Questao questao = (Questao) jComboBoxEscolhaQuestao.getSelectedItem();
            controle.mudarQuestaoAtual(questao);
            atualizarQuestaoTela();            
        }
    }

    private class CheckBoxHandler implements ItemListener {

        private boolean mudarSoma;

        public CheckBoxHandler() {
            this.mudarSoma = true;
        }

        public void setMudar(boolean mudar) {
            this.mudarSoma = mudar;
        }

        @Override
        public void itemStateChanged(ItemEvent e) {
            int somaAtual = 0;
            if (this.mudarSoma) {
                if (jCheckBoxOp01.isSelected()){
                    somaAtual += 1;
                }
                if (jCheckBoxOp02.isSelected()){
                    somaAtual += 2;
                }
                if (jCheckBoxOp04.isSelected()){
                    somaAtual += 4;
                }
                if (jCheckBoxOp08.isSelected()){
                    somaAtual += 8;
                }
                controle.registrarResposta(somaAtual);
                atualizarQuestaoTela();
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCorrigir;
    private javax.swing.JButton jButtonImagemQuestao;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JCheckBox jCheckBoxOp000;
    private javax.swing.JCheckBox jCheckBoxOp01;
    private javax.swing.JCheckBox jCheckBoxOp02;
    private javax.swing.JCheckBox jCheckBoxOp04;
    private javax.swing.JCheckBox jCheckBoxOp08;
    private javax.swing.JCheckBox jCheckBoxOp16;
    private javax.swing.JComboBox<String> jComboBoxEscolhaQuestao;
    private javax.swing.JLabel jLabelDisciplina;
    private javax.swing.JLabel jLabelNumeroQuestao;
    private javax.swing.JPanel jPanelComandos;
    private javax.swing.JPanel jPanelComandosDireita;
    private javax.swing.JPanel jPanelComandosEsquerda;
    private javax.swing.JPanel jPanelElementosQuestao;
    private javax.swing.JPanel jPanelElementosQuestaoDireita;
    private javax.swing.JPanel jPanelElementosQuestaoDireitaSomatorio;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerda;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerdaCabecalhoImagem;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerdaCabecalhoNumero;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerdaCentral;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerdaCentralCabecalho;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerdaCentralTexto;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerdaDisciplina;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerdaEnunciado;
    private javax.swing.JPanel jPanelEscolhaQuestao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaTextoQuestao;
    private javax.swing.JTextField jTextFieldSomatorio;
    // End of variables declaration//GEN-END:variables
}
