package aprendizado.poo.AulaPOO20304bd.src;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Valter Estevam
 */
public class TelaProdutosFrame extends javax.swing.JFrame {

    /**
     * Creates new form TelaProdutosFrame
     */
    public TelaProdutosFrame() {
        initComponents();
    }
    
    public TelaProdutosFrame(Produto p) {
        initComponents();
        jTextFieldId.setText(String.valueOf(p.getId()));
        jTextFieldNome.setText(p.getNome());
        jTextFieldPrecoUnitario.setText(String.valueOf(p.getPrecoUnitario()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBotoes = new javax.swing.JPanel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jPanelConteudo = new javax.swing.JPanel();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelPrecoUnitario = new javax.swing.JLabel();
        jTextFieldPrecoUnitario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelBotoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setMaximumSize(new java.awt.Dimension(120, 23));
        jButtonSalvar.setMinimumSize(new java.awt.Dimension(120, 23));
        jButtonSalvar.setPreferredSize(new java.awt.Dimension(120, 23));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jButtonSalvar);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(120, 23));
        jPanelBotoes.add(jButtonCancelar);

        getContentPane().add(jPanelBotoes, java.awt.BorderLayout.PAGE_END);

        jPanelConteudo.setLayout(new java.awt.GridLayout(3, 2));

        jLabelId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelId.setText("Id");
        jPanelConteudo.add(jLabelId);

        jTextFieldId.setEditable(false);
        jPanelConteudo.add(jTextFieldId);

        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNome.setText("Nome");
        jPanelConteudo.add(jLabelNome);
        jPanelConteudo.add(jTextFieldNome);

        jLabelPrecoUnitario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPrecoUnitario.setText("Preço Unitário");
        jPanelConteudo.add(jLabelPrecoUnitario);
        jPanelConteudo.add(jTextFieldPrecoUnitario);

        getContentPane().add(jPanelConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        try {
            String nome = jTextFieldNome.getText();
            double preco = Double.parseDouble(jTextFieldPrecoUnitario.getText());
            Produto p = new Produto(nome, preco);
            Conexao conexao = new Conexao();
            Connection con = conexao.conectar();
            String sqlInsertProduto
                    = "insert into produto (nome, preco_unitario) values (?, ?)";
            PreparedStatement ps = con.prepareStatement(sqlInsertProduto);
            ps.setString(1, p.getNome());
            ps.setDouble(2, p.getPrecoUnitario());
            ps.execute();
            ps.close();
            con.close();
            JOptionPane.showMessageDialog(this,
                    "Dados cadastrados com sucesso.",
                    "Sucesso",JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            ex.printStackTrace();
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(this,
                    "Formato de preço inválido","Erro", 
                    JOptionPane.ERROR_MESSAGE);
        }
        jTextFieldNome.setText("");
        jTextFieldPrecoUnitario.setText("");


    }//GEN-LAST:event_jButtonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProdutosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProdutosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProdutosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProdutosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProdutosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPrecoUnitario;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelConteudo;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPrecoUnitario;
    // End of variables declaration//GEN-END:variables
}
