package aprendizado.poo.AulaPOO208e1004.src;

import java.util.List;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ProdutoGUI extends javax.swing.JFrame {

    private List<Produto> produtos;
    private Produto produtoAtual;

    public ProdutoGUI() {
        initComponents();
        atualizarTabela();
        atualizarFormulario(new Produto());
    }

    public void atualizarFormulario(Produto p) {
        this.produtoAtual = p;
        this.jTextFieldNome.setText(p.getNome());
        this.jTextFieldPrecoUnitario.
                setText(String.valueOf(p.getPrecoUnitario()));
    }

    public void atualizarTabela() {

        //titulos - vetor de string
        String titulos[] = new String[]{"Nome", "Preço unitário"};

        //dados - matriz de string
        produtos = consultarProdutos();
        String dados[][] = new String[produtos.size()][2];
        int linha = 0;
        for (Produto p : produtos) {
            dados[linha][0] = p.getNome();
            dados[linha][1] = String.valueOf(p.getPrecoUnitario());
            linha++;
        }
        DefaultTableModel model = new DefaultTableModel(dados, titulos);
        jTableProdutos.setModel(model);
    }

    public List<Produto> consultarProdutos() {

        List<Produto> produtos = new ArrayList<>();
        try {
            Conexao conexao = new Conexao();
            Connection con = conexao.conectar();
            String sql = "select id, nome, preco_unitario from produto";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                int id = rs.getInt(1);
                String nome = rs.getString(2);
                double preco = rs.getDouble(3);
                Produto p = new Produto(id, nome, preco);
                produtos.add(p);
            }
            rs.close();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }
        return produtos;
    }

    public void cadastrarProduto(Produto p) {
        try {
            Conexao conexao = new Conexao();
            Connection con = conexao.conectar();
            String sql = "insert into produto (nome, preco_unitario) values (?,?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, p.getNome());
            ps.setDouble(2, p.getPrecoUnitario());
            ps.execute();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelForm = new javax.swing.JPanel();
        jPanelBotoesFormulario = new javax.swing.JPanel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jPanelCamposEntrada = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelPrecoUnitario = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldPrecoUnitario = new javax.swing.JTextField();
        jPanelTable = new javax.swing.JPanel();
        jPanelBotoesTabela = new javax.swing.JPanel();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jPanelComponenteTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanelForm.setLayout(new java.awt.BorderLayout());

        jPanelBotoesFormulario.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanelBotoesFormulario.add(jButtonSalvar);

        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jPanelBotoesFormulario.add(jButtonCancelar);

        jPanelForm.add(jPanelBotoesFormulario, java.awt.BorderLayout.PAGE_END);

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNome.setText("Nome");

        jLabelPrecoUnitario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPrecoUnitario.setText("Preço unitário");

        jTextFieldNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextFieldPrecoUnitario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelCamposEntradaLayout = new javax.swing.GroupLayout(jPanelCamposEntrada);
        jPanelCamposEntrada.setLayout(jPanelCamposEntradaLayout);
        jPanelCamposEntradaLayout.setHorizontalGroup(
            jPanelCamposEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCamposEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCamposEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCamposEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNome)
                    .addComponent(jTextFieldPrecoUnitario, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCamposEntradaLayout.setVerticalGroup(
            jPanelCamposEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCamposEntradaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelCamposEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCamposEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecoUnitario)
                    .addComponent(jTextFieldPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanelForm.add(jPanelCamposEntrada, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelForm, java.awt.BorderLayout.PAGE_START);

        jPanelTable.setLayout(new java.awt.BorderLayout());

        jPanelBotoesTabela.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonAlterar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAlterar.setText("Alterar");
        jPanelBotoesTabela.add(jButtonAlterar);

        jButtonExcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jPanelBotoesTabela.add(jButtonExcluir);

        jPanelTable.add(jPanelBotoesTabela, java.awt.BorderLayout.PAGE_END);

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProdutos);

        javax.swing.GroupLayout jPanelComponenteTabelaLayout = new javax.swing.GroupLayout(jPanelComponenteTabela);
        jPanelComponenteTabela.setLayout(jPanelComponenteTabelaLayout);
        jPanelComponenteTabelaLayout.setHorizontalGroup(
            jPanelComponenteTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComponenteTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelComponenteTabelaLayout.setVerticalGroup(
            jPanelComponenteTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComponenteTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelTable.add(jPanelComponenteTabela, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelTable, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        try {
            String nome = jTextFieldNome.getText();
            double preco = Double.parseDouble(jTextFieldPrecoUnitario.getText());
            produtoAtual.setNome(nome);
            produtoAtual.setPrecoUnitario(preco);
            if (produtoAtual.getId() == 0){
                //inserir
                cadastrarProduto(produtoAtual);
            }else{
                //alterar produto
            }
            atualizarFormulario(new Produto());
            atualizarTabela();            
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this,"Formato inválido de preço.");
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPrecoUnitario;
    private javax.swing.JPanel jPanelBotoesFormulario;
    private javax.swing.JPanel jPanelBotoesTabela;
    private javax.swing.JPanel jPanelCamposEntrada;
    private javax.swing.JPanel jPanelComponenteTabela;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPrecoUnitario;
    // End of variables declaration//GEN-END:variables
}
